export const LOAD_USERS_LOADING = 'LOAD_USERS_LOADING';
export const LOAD_USERS_ERROR = 'LOAD_USERS_ERROR';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const SET_ACTIVE_THEME = 'SET_ACTIVE_THEME';
