export const STORE_ALL_STOCKS = 'STORE_ALL_STOCKS';
export const FILTER_STOCKS = 'FILTER_STOCKS';
export const RESET_STOCKS = 'RESET_STOCKS';
export const SET_SELECTED_STOCK = 'SET_SELECTED_STOCK';
export const RESET_SELECTED_STOCK = 'RESET_SELECTED_STOCK';
export const ADD_OR_EDIT_STOCK_TO_SELECTED = 'ADD_OR_EDIT_STOCK_TO_SELECTED';
